version: '3'

services:
  db:
    image: postgres

    restart: always

    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: nestjs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123

  # test-db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_PASSWORD: pass123
